---
require:
  - rubocop-performance
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/*'
    - 'scripts/**/*'
    - 'scripts/*'
    - 'script/**/*'
    - 'one-time/**/*'
    - 'one-timer/**/*'
    - 'one-timers/**/*'
    - 'db/**/*'
    - 'config.ru'
    - 'Rakefile'
    - 'lib/templates/**/*'
    - 'vender/**/*'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
Style/GuardClause:
  MinBodyLength: 1
  Enabled: false
Style/AndOr:
  Enabled: false
  EnforcedStyle: conditionals
Style/PercentLiteralDelimiters:
  PreferredDelimiters: {}
  Enabled: false
Style/Alias:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
# ->() {}  -- lambda {|a| }
Style/Lambda:
  EnforcedStyle: 'literal'
# if bla.nil?  --  if bla == nil
Style/NilComparison:
  Enabled: false
# Ruby 3
Style/FrozenStringLiteralComment:
  Enabled: false
# def bla; end
Style/EmptyMethod:
  Enabled: false
# [ "700", "200" ] -> %w[w w]
Style/WordArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/RedundantArgument:
  Enabled: false
Style/EndlessMethod:
  Enabled: allow_always
Style/NegatedIf:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false

Layout/LineLength:
  Max: 150
  Exclude:
    - spec/**/*
Layout/DotPosition:
  Enabled: false
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['task', 'namespace', 'get', 'post', 'describe', 'context', 'specify', 'it', 'route_param', 'draw', 'register', 'register_page', 'controller', 'included', 'params', 'resource', 'with_options', 'use_cassette', 'configure', 'transaction']
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  CountKeywordArgs: false
  Exclude:
    - "app/graphql/types/**/*.rb"
Metrics/CyclomaticComplexity:
  Max: 15

Performance/StringReplacement:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
Naming/PredicateName:
  Enabled: false
Lint/DuplicateBranch:
  IgnoreLiteralBranches: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - app/views/components/**/*.rb
Lint/SuppressedException:
  Enabled: false
